### ISSUE TITLE
Crowdsourcing

### ISSUE THREAD

**Issue by schmitts** [rasteri/SC1000#1]
Hi!

Thanks for your amazing project. Do you plan to crowdsource the production?

Thanks,

Sebastian

**Comment by ben-ward** [comment]
Also came here to say this. I'm a maker but I'm already up to my ears in projects.
I think if it could scratch a similar itch that Teenage Engineering's Pocket Operators do 
https://www.teenageengineering.com/products/po
So cool!

**Comment by rasteri** [comment]
Hi! thanks for your interest.

I'm working with Ramin from PortablismGear to produce some. Crowdfunding shouldn't be neccesary, but I'll certainly consider it in the future once we have the design locked :)

Cheers
Andy

**Comment by schmitts** [comment]
It arrived! https://portablismgear.com/sc1000-digital-scratch-instrument.html
