### ISSUE TITLE
Link to new Firmware with the Midi stuff?

### ISSUE THREAD

**Issue by 10shun** [rasteri/SC1000#12]
Hello, i dont have Facebook so i cannot view any of the news that is developing with the Sc1000.
It seems to be set for private or members only.

Is there any way you can upload the most recent firmware to the sc1000?

And if so will i be able to just drag and drop the new version of xwax(firmware) on the thumb drive thats connected to the sc1000?

**Comment by rasteri** [comment]
http://rasteri.com/wiki/SC1000_Beta

**Comment by 10shun** [comment]
Thanks!!

**Comment by rasteri** [comment]
No worries! Let me know how you got on. I didn't publicize the link because I was worried it was going to fuck up people's SCs but there's been no problems so far so I think you'll be ok

**Comment by 10shun** [comment]
The Update went perfectly. I followed the instructions listed on the link and update went perfectly.
Now i just gotta find a device to mess with the midi function.

**Comment by rasteri** [comment]
There's a new version with recording support and some other bugfixes out now - http://rasteri.com/wiki/SC1000_Beta
