### ISSUE TITLE
Midi documentation anywhere?

### ISSUE THREAD

**Issue by TeddyK76** [rasteri/SC1000#13]
I've been messing with this unit for almost a year. The added midi control would be great to use.....but there is literally nothing in any of the firmware that explains it in laymen's terms. I have a drum controller and keyboard controller. Have messed with midi channels and all that but nothing works. I'm not going to use Lemur as it's quite shit.

**Comment by rasteri** [comment]
http://rasteri.com/SC1000_MIDI_chart.png
