### ISSUE TITLE
SC500 image

### ISSUE THREAD

**Issue by ximo23** [rasteri/SC1000#14]
Hi,
I have mounted a SC500 and when I try to run the SD Image posted in the repository it doesn't work properly, it behavies like a SC1000. The problem is that the buttons map is different and I can't change de volume, the beat or the sample.
I think that I can solve the problem updating de firmware, the only way that I found is like in this video, but the button map is different and there are not potentiometers in SC500:
https://www.youtube.com/watch?v=4zC_MFa_150&t=50s

How can I prepare a correct SD image for the SC500? It's possible to do a firmware update overwriting the sistem files with the new software?
http://rasteri.com/ website is not working now, maybe this informatin is there.

Someone can share a valid SD image for the SC500?

Thanks

**Comment by rasteri** [comment]
You need to update to the latest image. Update procedure for the 500 is the same as the 1000, but you hold down the beat VOL button instead of the beat track select button.
