### ISSUE TITLE
Jog Wheel PCB Dimensions

### ISSUE THREAD

**Issue by markprotas** [rasteri/SC1000#2]
The dimensions of the jog wheel are a mystery to me- viewing the gerber files and attempting to run some dimension analysis on them, it seems like I get something like 1200 x 1200 mm, which certainly doesn't make any sense given the nature of the machine.  How can I figure out the actual jog wheel dimensions for fabrication?

**Comment by rasteri** [comment]
It's 120mm X 120mm.
