### ISSUE TITLE
CPL pick&place file for sc500

### ISSUE THREAD

**Issue by DubbyLabby** [rasteri/SC1000#20]
Hi Andy,
I noticed you have the CVS file for sc1000 but not for sc500. I'm trying to calculate how much it will cost to send jlcpcb for some ready units but not luck.

Can you advise me somehow? 

Thanks

**Comment by DubbyLabby** [comment]
Not completed but neither needed anymore...

**Comment by flintspike** [comment]
This is a pretty old comment, but I dont suppose you have either of those files?

**Comment by DubbyLabby** [comment]
Hi!
If you read my previous comment you will notice that never happened… but also I don’t need them neither.

Sorry mate 🙏🏻
