### ISSUE TITLE
May I suggest SHIFT+Start to Play/Stop the beat?

### ISSUE THREAD

**Issue by SaccoSVD** [rasteri/SC1000#25]
Would be nice to do that in the same way you can start/stop the sample "platter"

That in order to not have to adjust volumes all the time. (Yes I'm aware I can cut the beat with the fader in v 1.7Alpha)

Thank you :)

**Comment by rasteri** [comment]
You could actually add this yourself. I think the following line should work (in 1.7 anyway) if you add it to scsettings.txt

`gpio=1,16,1,3,CH0_STARTSTOP`

I can't test it just now but let me know if it works

**Comment by SaccoSVD** [comment]
Niiiice! it does graciously works!

Thank you!
