### ISSUE TITLE
MCP23017 connection in new firmware

### ISSUE THREAD

**Issue by koitzroller** [rasteri/SC1000#32]
Hi folks!

I tried to connect a MCP23017 as [Rasteri said in his wiki](http://rasteri.com/SC1000_MCP23017_Connection_Diagram.pdf) in a SC1000MK2 from Portablismgear, but nothing occurs. Tried to add # to comment lines in scsettings.txt with input conflict (gpio=1,15 and 16) but no results. It seems MCP23017 address board is 000, right? I even explore code to check if is hardwired to other port, but I didn't find it. Any thoughts?

Regards

**Comment by DubbyLabby** [comment]
Are you running the latest firmware?
http://rasteri.com/wiki/SC1000_Firmware_Update

**Comment by koitzroller** [comment]
Yes, I'm running the last firmware.

Finally I discovered the problem: by default MCP23017 board I'm using (Waveshare) is on 111 address w/o solder pins instead of 000 needed by SC1000 🤦‍♂️.

Now works flawlessly.

Regards
