### ISSUE TITLE
Screws for USB connector J6

### ISSUE THREAD

**Issue by schmitts** [rasteri/SC1000#5]
Which screw type is to use for the USB connector J6?

**Comment by s3kn0tr0n1c** [comment]
I used M1.6mm. I bought them and the  nuts of ebay.

https://www.ebay.co.uk/itm/321168183114
https://www.ebay.co.uk/itm/111309628000

**Comment by rasteri** [comment]
I used M1.4 screws and nuts. Best get em from ebay.
