### ISSUE TITLE
Expected sample rate of wav files

### ISSUE THREAD

**Issue by schmitts** [rasteri/SC1000#6]
What's the expected sample rate of the wav files? The files I've tested seem to be played back at at least twice the correct speed.

General
Complete name                            : /usr/share/emscripten/tests/sounds/the_entertainer.wav
Format                                   : Wave
File size                                : 258 KiB
Duration                                 : 3 s 0 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 706 kb/s

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 3 s 0 ms
Bit rate mode                            : Constant
Bit rate                                 : 705.6 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 258 KiB (100%)

**Comment by s3kn0tr0n1c** [comment]
No idea . Ive just been using mp3s at 320kb. Ive saw this happen on samples before. Id try a wav at 1411kbps to see if it works.

Good tip for your beats is to just use short loops(as used in loopers). They automatically loop on SC1000.

**Comment by rasteri** [comment]
The SC1000 expects 48kHz 16-bit signed stereo .wav files. That file you have is mono 44kHz so it won't play back at the correct speed.

**Comment by microfx** [comment]
Would be nice if you could write that into the "manual"... I had to find that information here.
